export const PERMISSION_GROUPS = [
  {
    id: 'others',
    title: 'Others',
    items: [
      { id: 'service_staff', label: 'Service staff' },
      { id: 'export_buttons', label: 'View export to buttons (csv/excel/print/pdf) on tables' },
    ],
  },
  {
    id: 'user',
    title: 'User',
    items: [
      { id: 'view_user', label: 'View user' },
      { id: 'add_user', label: 'Add user' },
      { id: 'edit_user', label: 'Edit user' },
      { id: 'delete_user', label: 'Delete user' },
    ],
  },
  {
    id: 'roles',
    title: 'Roles',
    items: [
      { id: 'view_role', label: 'View role' },
      { id: 'add_role', label: 'Add Role' },
      { id: 'edit_role', label: 'Edit Role' },
      { id: 'delete_role', label: 'Delete role' },
    ],
  },
  {
    id: 'supplier',
    title: 'Supplier',
    items: [
      { id: 'view_all_supplier', label: 'View all supplier' },
      { id: 'view_own_supplier', label: 'View own supplier' },
      { id: 'add_supplier', label: 'Add supplier' },
      { id: 'edit_supplier', label: 'Edit supplier' },
      { id: 'delete_supplier', label: 'Delete supplier' },
    ],
  },
  {
    id: 'customer',
    title: 'Customer',
    items: [
      { id: 'view_all_customer', label: 'View all customer' },
      { id: 'view_own_customer', label: 'View own customer' },
      { id: 'no_sell_1m', label: 'View customers with no sell from one month only' },
      { id: 'no_sell_3m', label: 'View customers with no sell from three months only' },
      { id: 'no_sell_6m', label: 'View customers with no sell from six months only' },
      { id: 'no_sell_1y', label: 'View customers with no sell from one year only' },
      { id: 'irrespective_sell', label: 'View customers irrespective of their sell' },
      { id: 'add_customer', label: 'Add customer' },
      { id: 'edit_customer', label: 'Edit customer' },
      { id: 'delete_customer', label: 'Delete customer' },
    ],
  },
  {
    id: 'product',
    title: 'Product',
    items: [
      { id: 'view_product', label: 'View product' },
      { id: 'add_product', label: 'Add product' },
      { id: 'edit_product', label: 'Edit product' },
      { id: 'delete_product', label: 'Delete product' },
      { id: 'add_opening_stock', label: 'Add Opening Stock' },
      { id: 'view_purchase_price', label: 'View Purchase Price' },
    ],
  },
  {
    id: 'purchase_stock_adjustment',
    title: 'Purchase & Stock Adjustment',
    items: [
      { id: 'view_all', label: 'View all Purchase & Stock Adjustment' },
      { id: 'view_own', label: 'View own Purchase & Stock Adjustment' },
      { id: 'add', label: 'Add purchase & Stock Adjustment' },
      { id: 'edit', label: 'Edit purchase & Stock Adjustment' },
      { id: 'delete', label: 'Delete purchase & Stock Adjustment' },
      { id: 'add_purchase_payment', label: 'Add purchase payment' },
      { id: 'edit_purchase_payment', label: 'Edit purchase payment' },
      { id: 'delete_purchase_payment', label: 'Delete purchase payment' },
      { id: 'update_status', label: 'Update Status' },
    ],
  },
  {
    id: 'purchase_requisition',
    title: 'Purchase Requisition',
    items: [
      { id: 'view_all', label: 'View all purchase requisition' },
      { id: 'view_own', label: 'View own purchase requisition' },
      { id: 'create', label: 'Create purchase requisition' },
      { id: 'delete', label: 'Delete purchase requisition' },
    ],
  },
  {
    id: 'purchase_order',
    title: 'Purchase Order',
    items: [
      { id: 'view_all', label: 'View all purchase order' },
      { id: 'view_own', label: 'View own purchase order' },
      { id: 'create', label: 'Create purchase order' },
      { id: 'edit', label: 'Edit purchase order' },
      { id: 'delete', label: 'Delete purchase order' },
    ],
  },
  {
    id: 'pos',
    title: 'POS',
    items: [
      { id: 'view_pos_sell', label: 'View POS sell' },
      { id: 'add_pos_sell', label: 'Add POS sell' },
      { id: 'edit_pos_sell', label: 'Edit POS sell' },
      { id: 'delete_pos_sell', label: 'Delete POS sell' },
      { id: 'edit_price_from_pos', label: 'Edit product price from POS screen' },
      { id: 'edit_discount_from_pos', label: 'Edit product discount from POS screen' },
      { id: 'add_edit_payment', label: 'Add/Edit Payment' },
      { id: 'print_invoice', label: 'Print Invoice' },
      { id: 'disable_multiple_pay', label: 'Disable Multiple Pay' },
      { id: 'disable_draft', label: 'Disable Draft' },
      { id: 'disable_express_checkout', label: 'Disable Express Checkout' },
      { id: 'disable_discount', label: 'Disable Discount' },
      { id: 'disable_suspend_sale', label: 'Disable Suspend Sale' },
      { id: 'disable_credit_sale_button', label: 'Disable credit sale button' },
      { id: 'disable_quotation', label: 'Disable Quotation' },
      { id: 'disable_card', label: 'Disable Card' },
    ],
  },
  {
    id: 'sell',
    title: 'Sell',
    items: [
      { id: 'view_all', label: 'View all sell' },
      { id: 'view_own', label: 'View own sell only' },
      { id: 'view_paid', label: 'View paid sells only' },
      { id: 'view_due', label: 'View due sells only' },
      { id: 'view_partially_paid', label: 'View partially paid sells only' },
      { id: 'view_overdue', label: 'View overdue sells only' },
      { id: 'add', label: 'Add Sell' },
      { id: 'update', label: 'Update Sell' },
      { id: 'delete', label: 'Delete Sell' },
      { id: 'commission_agent_view_own', label: 'Commission agent can view their own sell' },
      { id: 'add_payment', label: 'Add sell payment' },
      { id: 'edit_payment', label: 'Edit sell payment' },
      { id: 'delete_payment', label: 'Delete sell payment' },
      { id: 'edit_price_from_sales', label: 'Edit product price from sales screen' },
      { id: 'edit_discount_from_sales', label: 'Edit product discount from Sale screen' },
      { id: 'discount_crud', label: 'Add/Edit/Delete Discount' },
      { id: 'access_types_of_service', label: 'Access types of service' },
      { id: 'sell_return_all', label: 'Access all sell return' },
      { id: 'sell_return_own', label: 'Access own sell return' },
      { id: 'add_edit_invoice_number', label: 'Add edit invoice number' },
    ],
  },
  {
    id: 'sales_order',
    title: 'Sales Order',
    items: [
      { id: 'view_all', label: 'View all sales order' },
      { id: 'view_own', label: 'View own sales order' },
      { id: 'create', label: 'Create sales order' },
      { id: 'edit', label: 'Edit sales order' },
      { id: 'delete', label: 'Delete sales order' },
    ],
  },
  {
    id: 'draft',
    title: 'Draft',
    items: [
      { id: 'view_all', label: 'View all drafts' },
      { id: 'view_own', label: 'View own drafts' },
      { id: 'edit', label: 'Edit draft' },
      { id: 'delete', label: 'Delete draft' },
    ],
  },
  {
    id: 'quotation',
    title: 'Quotation',
    items: [
      { id: 'view_all', label: 'View all quotations' },
      { id: 'view_own', label: 'View own quotations' },
      { id: 'edit', label: 'Edit quotation' },
      { id: 'delete', label: 'Delete quotation' },
    ],
  },
  {
    id: 'shipments',
    title: 'Shipments',
    items: [
      { id: 'access_all', label: 'Access all shipments' },
      { id: 'access_own', label: 'Access own shipments' },
      { id: 'access_pending_only', label: 'Access pending shipments only' },
      { id: 'commission_agent_access_own', label: 'Commission agent can access their own shipments' },
    ],
  },
  {
    id: 'cash_register',
    title: 'Cash Register',
    items: [
      { id: 'view', label: 'View cash register' },
      { id: 'close', label: 'Close cash register' },
    ],
  },
  {
    id: 'brand',
    title: 'Brand',
    items: [
      { id: 'view', label: 'View brand' },
      { id: 'add', label: 'Add brand' },
      { id: 'edit', label: 'Edit brand' },
      { id: 'delete', label: 'Delete brand' },
    ],
  },
  {
    id: 'tax_rate',
    title: 'Tax rate',
    items: [
      { id: 'view', label: 'View tax rate' },
      { id: 'add', label: 'Add tax rate' },
      { id: 'edit', label: 'Edit tax rate' },
      { id: 'delete', label: 'Delete tax rate' },
    ],
  },
  {
    id: 'unit',
    title: 'Unit',
    items: [
      { id: 'view', label: 'View unit' },
      { id: 'add', label: 'Add unit' },
      { id: 'edit', label: 'Edit unit' },
      { id: 'delete', label: 'Delete unit' },
    ],
  },
  {
    id: 'category',
    title: 'Category',
    items: [
      { id: 'view', label: 'View category' },
      { id: 'add', label: 'Add category' },
      { id: 'edit', label: 'Edit category' },
      { id: 'delete', label: 'Delete category' },
    ],
  },
  {
    id: 'report',
    title: 'Report',
    items: [
      { id: 'purchase_sell', label: 'View purchase & sell report' },
      { id: 'tax_report', label: 'View Tax report' },
      { id: 'supplier_customer_report', label: 'View Supplier & Customer report' },
      { id: 'expense_report', label: 'View expense report' },
      { id: 'profit_loss_report', label: 'View profit/loss report' },
      { id: 'stock_reports', label: 'View stock report, stock adjustment report & stock expiry report' },
      { id: 'trending_product', label: 'View trending product report' },
      { id: 'register_report', label: 'View register report' },
      { id: 'sales_representative_report', label: 'View sales representative report' },
      { id: 'product_stock_value', label: 'View product stock value' },
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    items: [
      { id: 'business_settings', label: 'Access business settings' },
      { id: 'barcode_settings', label: 'Access barcode settings' },
      { id: 'invoice_settings', label: 'Access invoice settings' },
      { id: 'printers', label: 'Access printers' },
    ],
  },
  {
    id: 'expense',
    title: 'Expense',
    items: [
      { id: 'access_all', label: 'Access all expenses' },
      { id: 'view_own', label: 'View own expense only' },
      { id: 'add', label: 'Add Expense' },
      { id: 'edit', label: 'Edit Expense' },
      { id: 'delete', label: 'Delete Expense' },
    ],
  },
  { id: 'home', title: 'Home', items: [{ id: 'view_home_data', label: 'View Home data' }] },
  {
    id: 'account',
    title: 'Account',
    items: [
      { id: 'access_accounts', label: 'Access Accounts' },
      { id: 'edit_transaction', label: 'Edit account transaction' },
      { id: 'delete_transaction', label: 'Delete account transaction' },
    ],
  },
  {
    id: 'bookings',
    title: 'Bookings',
    items: [
      { id: 'all', label: 'Add/Edit/View all bookings' },
      { id: 'own', label: 'Add/Edit/View own bookings' },
    ],
  },
  {
    id: 'selling_price_groups',
    title: 'Selling Price Groups',
    items: [
      { id: 'access', label: 'Access selling price groups' },
      { id: 'default_selling_price', label: 'Default Selling Price' },
    ],
  },
  { id: 'restaurant', title: 'Restaurant', items: [{ id: 'access_tables', label: 'Access tables' }] },
  {
    id: 'accounting',
    title: 'Accounting',
    items: [
      { id: 'access_module', label: 'Access Accounting Module' },
      { id: 'manage_accounts', label: 'Manage Accounts' },
      { id: 'view_journal', label: 'View Journal' },
      { id: 'add_journal', label: 'Add Journal' },
      { id: 'edit_journal', label: 'Edit Journal' },
      { id: 'delete_journal', label: 'Delete Journal' },
      { id: 'map_transactions', label: 'Map Transactions' },
      { id: 'view_transfer', label: 'View Transfer' },
      { id: 'add_transfer', label: 'Add Transfer' },
      { id: 'edit_transfer', label: 'Edit Transfer' },
      { id: 'delete_transfer', label: 'Delete Transfer' },
      { id: 'manage_budget', label: 'Manage Budget' },
      { id: 'view_reports', label: 'View Reports' },
    ],
  },
  {
    id: 'aiassistance',
    title: 'AiAssistance',
    items: [{ id: 'lang.access_aiassistance_module', label: 'aiassistance::lang.access_aiassistance_module' }],
  },
  {
    id: 'crm',
    title: 'Crm',
    items: [
      { id: 'follow_up_all', label: 'Access all follow up' },
      { id: 'follow_up_own', label: 'Access own follow up' },
      { id: 'leads_all', label: 'Access all leads' },
      { id: 'leads_own', label: 'Access own leads' },
      { id: 'campaigns_all', label: 'Access all campaigns' },
      { id: 'campaigns_own', label: 'Access own campaigns' },
      { id: 'contact_login', label: 'Access contact login' },
      { id: 'sources', label: 'Access sources' },
      { id: 'life_stage', label: 'Access life stage' },
      { id: 'proposal', label: 'Access proposal' },
    ],
  },
  {
    id: 'essentials',
    title: 'Essentials',
    items: [
      { id: 'leave_type_crud', label: 'Add/Edit/View/Delete leave type' },
      { id: 'leave_all_crud', label: 'Add/Edit/View/Delete all leave' },
      { id: 'leave_own', label: 'Add/View own leave' },
      { id: 'approve_leave', label: 'Approve Leave' },
      { id: 'attendance_all_crud', label: 'Add/Edit/View/Delete all attendance' },
      { id: 'attendance_own', label: 'View own attendance' },
      { id: 'attendance_web', label: 'Allow users to enter their own attendance from web' },
      { id: 'attendance_api', label: 'Allow users to enter their own attendance from api' },
      { id: 'view_pay_component', label: 'View Pay Component' },
      { id: 'add_pay_component', label: 'Add Pay Component' },
      { id: 'department_crud', label: 'Add/Edit/View/Delete department' },
      { id: 'designation_crud', label: 'Add/Edit/View/Delete designation' },
      { id: 'payroll_view_all', label: 'View all Payroll' },
      { id: 'payroll_add', label: 'Add Payroll' },
      { id: 'payroll_edit', label: 'Edit Payroll' },
      { id: 'payroll_delete', label: 'Delete Payroll' },
      { id: 'todos_assign', label: "Assign To Do's to others" },
      { id: 'todos_add', label: "Add To Do's" },
      { id: 'todos_edit', label: "Edit To Do's" },
      { id: 'todos_delete', label: "Delete To Do's" },
      { id: 'message_create', label: 'Create Message' },
      { id: 'message_view', label: 'View Message' },
      { id: 'sales_targets', label: 'Access Sales Targets' },
    ],
  },
  {
    id: 'manufacturing',
    title: 'Manufacturing',
    items: [
      { id: 'view_recipe', label: 'View Recipe' },
      { id: 'add_recipe', label: 'Add Recipe' },
      { id: 'edit_recipe', label: 'Edit Recipe' },
      { id: 'access_production', label: 'Access Production' },
    ],
  },
  {
    id: 'project',
    title: 'Project',
    items: [
      { id: 'create', label: 'Create Project' },
      { id: 'edit', label: 'Edit Project' },
      { id: 'delete', label: 'Delete Project' },
    ],
  },
  {
    id: 'repair',
    title: 'Repair',
    items: [
      { id: 'add_invoice', label: 'Add Invoice' },
      { id: 'edit_invoice', label: 'Edit Invoice' },
      { id: 'view_all_invoice', label: 'View all invoice' },
      { id: 'view_own_invoice', label: 'View own invoice' },
      { id: 'delete_invoice', label: 'Delete Invoice' },
      { id: 'change_invoice_status', label: 'Change Invoice Status' },
      { id: 'job_sheet_status_crud', label: 'Add/Edit/Delete Job Sheet Status' },
      { id: 'add_job_sheet', label: 'Add job sheet' },
      { id: 'edit_job_sheet', label: 'Edit Job Sheet' },
      { id: 'delete_job_sheet', label: 'Delete Job Sheet' },
      { id: 'view_only_assigned', label: 'View Only Assigned Job Sheet' },
      { id: 'view_all', label: 'View All Job Sheets' },
    ],
  },
  { id: 'superadmin', title: 'Superadmin', items: [{ id: 'package_subscriptions', label: 'Access package subscriptions' }] },
  {
    id: 'woocommerce',
    title: 'Woocommerce',
    items: [
      { id: 'sync_product_categories', label: 'Sync Product Categories' },
      { id: 'sync_products', label: 'Sync Products' },
      { id: 'sync_orders', label: 'Sync Orders' },
      { id: 'map_tax_rates', label: 'Map Tax Rates' },
      { id: 'access_api_settings', label: 'Access Woocommerce API settings' },
    ],
  },
];
